name: m3o
version: 1.0.190
homepage: https://github.com/m3o/m3o-dart
description: This is the Dart client to access APIs like DB, Functions, App, Events and more on the M3O Platform

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  test: ^1.16.0
  freezed: ^2.1.0
  build_runner: ^2.1.5
  json_serializable: ^6.1.3
  
dependencies: 
  json_annotation: ^4.4.0
  freezed_annotation: ^2.1.0